### ISSUE TITLE
Socket.io is not identified on frontend 

### ISSUE THREAD

**Issue by shubhjain7** [bradtraversy/chatcord#11]
After installing every library including socket.io,
 The 3rd last line in chat.html  <script src="/socket.io/socket.io.js" >
  </script> .This is giving  me error as:
 GET http://localhost:3000/socket.io/socket.io.js net::ERR_ABORTED 404 (Not Found)
and main.js:2 Uncaught ReferenceError: io is not defined
    at main.js:2
Please help me resolve this issue.

**Comment by zelotbe** [comment]
Hi,
Did you fix this? 
Having the same issue atm

**Comment by AYehia0** [comment]
@zelotbe I had the same problem but i fixed it, here is the commit : https://github.com/AYehia0/Chatty/commit/27f6b4fb7c1beba81a9ea0fd6cba97c4691cd105
