### ISSUE TITLE
Issues while running my application 

### ISSUE THREAD

**Issue by ayushnanda21** [bradtraversy/chatcord#24]
I am confident my code is correct. But everytime I enter as user, its not showing and welcome message and not  the messages a user send. I everytime I click on leave room it gives out error "formatMessage function not found" in my terminal. I have attached my repo link. Can anyone tell the error and help me to resolve 

 (https://github.com/ayushnanda21/Chat-Flow)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/64643319/96832989-4fe73a80-145d-11eb-8659-7a706b14932a.gif)

**Comment by nsachin08** [comment]
Is your issue resolved ?

**Comment by ayushnanda21** [comment]
Yes perfectly working
