### ISSUE TITLE
Someone copied the exact thing but just changed the css lmfao

### ISSUE THREAD

**Issue by focat69** [bradtraversy/chatcord#32]
Here is the website (scroll down the comments and u'll see)
https://repl.it/talk/share/Froggy-Chatroom-Sneak-peek/123002

**Comment by Sanchaksh** [comment]
Well no one can help with this right XOXO

**Comment by focat69** [comment]
Hmm, the owner can.

**Comment by focat69** [comment]
lmao im closing this

**Comment by Sanchaksh** [comment]
LOL

**Comment by focat69** [comment]
lol
